[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.136.1"}
sqlalchemy = "^2.0.49"
openpyxl = "^3.1.5"
pydantic = {extras = ["email"], version = "^2.13.4"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.28"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
